### ISSUE TITLE
Functional Analysis markdown template crashes

### ISSUE THREAD

**Issue by adam-forward** [hbc/bcbioRNASeq#153]
I am trying to run the markdown template for FA, but it is still expecting a DESeqResults object, but that was replaced in v 0.3.3 with DGEList.

The error I get is:
```
label: load-res
> Importing bcb_res_tbl_list.rds using base::`readRDS()`.

Quitting from lines 114-118 (03_FA.Rmd) 
Error: is(res, "DESeqResults") is not TRUE
Execution halted
```
What should I do to switch things over?

**Comment by mjsteinbaugh** [comment]
Hi @adam-forward , I'm taking a look at the template and will get back to you with some suggestions.

**Comment by mjsteinbaugh** [comment]
Can you post a copy of the object you're trying to use as input for the functional analysis template? I'm guessing you're using an edgeR `DGEList` object instead of a `DESeqDataSet` and `DESeqResults` correct?

**Comment by adam-forward** [comment]
Hi @mjsteinbaugh , yes I am using DGEList, although a DESeqDataSet is still being generated from the differential expression R Markdown template, so I have that too.

Here is the file for the DGEList I am trying to use: https://drive.google.com/file/d/1C5a60CxutyXUnfbgX5fFqx5LlmZ2oTCZ/view?usp=sharing

And here's the parameter section of the markdown I am using:
```
---
## Alternatively, consider using the pfgsea package for fast preranked GSEA.
##
## - KEGG supported organisms
##   http://www.genome.jp/kegg/catalog/org_list.html
## - OrgDb supported organisms
##   http://bioconductor.org/packages/release/BiocViews.html#___OrgDb
##
## Updated 2019-09-17.
params:
  title: "Functional analysis with clusterProfiler"
  ## DESeqDataSet object.
  dds_file: "data/2020-06-04/bcb_dds.rds"
  ## DESeqResults object.
  res_file: "data/2020-06-04/bcb_res_tbl_list.rds"
  organism: "Homo sapiens"
  go_class: "BP"
  data_dir: !r file.path("data", Sys.Date())
  output_dir: !r file.path("results", Sys.Date(), "functional-analysis")
  ## Pathview KEGG plots tend to be slow to render.
  pathview: FALSE
title: "`r params$title`"
author: "`r getOption('author')`"
date: "`r Sys.Date()`"
bibliography: bibliography.bib
---
```
